# -*- coding: utf-8 -*-
"""supermarket_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUYvHGwyLrO78bS1_VhK1pWAOwgUJMfQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv("/content/SuperMarket Analysis.csv")
df.head()

df['Date']=pd.to_datetime(df['Date'])

df['Time']=pd.to_datetime(df['Time'],format='%I:%M:%S %p').dt.time
df.head()

df['day_of_week'] = df['Date'].dt.day_name()
df['month'] = df['Date'].dt.month_name()

df['order_hour'] = pd.to_datetime(df['Time'].astype(str)).dt.hour

# Weekend flag
df['is_weekend'] = df['day_of_week'].isin(['Saturday', 'Sunday']).astype(int)

# Basket size = quantity
df['basket_size'] = df['Quantity']

# Total Revenue = Sales
df['Revenue'] = df['Sales']

# Profit = gross income
df['Profit'] = df['gross income']

df.head()

clean_path = "/content/cleaned.csv"
df.to_csv(clean_path, index=False)

print("Clean file saved:", clean_path)

import pandas as pd

df = pd.read_csv("/content/cleaned.csv")
df.head()

print("shape: ",df.shape)
print("\ncolumns:",df.columns.tolist())

print(df.info())

df.describe()

total_revenue = df['Revenue'].sum()
total_profit = df['Profit'].sum()
avg_rating = df['Rating'].mean()
total_transactions = df['Invoice ID'].nunique()
avg_basket_size = df['basket_size'].mean()

print("Total Revenue:", round(total_revenue, 2))
print("Total Profit:", round(total_profit, 2))
print("Average Rating:", round(avg_rating, 2))
print("Total Transactions:", total_transactions)
print("Average Basket Size:", round(avg_basket_size, 2))

# Revenue by Branch
rev_branch = df.groupby('Branch')['Revenue'].sum().sort_values(ascending=False)
print("\nRevenue by Branch:")
print(rev_branch)

# Revenue by City
rev_city = df.groupby('City')['Revenue'].sum().sort_values(ascending=False)
print("\nRevenue by City:")
print(rev_city)

# Profit margin by City
profit_margin_city = (df.groupby('City')['Profit'].sum() / df.groupby('City')['Revenue'].sum()).sort_values(ascending=False)
print("\nProfit Margin by City:")
print((profit_margin_city * 100).round(2).astype(str) + "%")

# Revenue by Product line
rev_product = df.groupby('Product line')['Revenue'].sum().sort_values(ascending=False)
print("\nRevenue by Product line:")
print(rev_product)

# Average Rating by Product line
rating_product = df.groupby('Product line')['Rating'].mean().sort_values(ascending=False)
print("\nAverage Rating by Product line:")
print(rating_product.round(2))

# Profit by Product line
profit_product = df.groupby('Product line')['Profit'].sum().sort_values(ascending=False)
print("\nProfit by Product line:")
print(profit_product)

# Revenue by Customer type
rev_cust_type = df.groupby('Customer type')['Revenue'].sum()
print("\nRevenue by Customer type:")
print(rev_cust_type)

# Average basket size by Customer type
basket_cust_type = df.groupby('Customer type')['basket_size'].mean()
print("\nAverage basket size by Customer type:")
print(basket_cust_type.round(2))

# Revenue by Gender
rev_gender = df.groupby('Gender')['Revenue'].sum()
print("\nRevenue by Gender:")
print(rev_gender)

# Payment methods
payment_counts = df['Payment'].value_counts()
print("\nPayment method counts:")
print(payment_counts)

# Revenue by day of week
rev_day = df.groupby('day_of_week')['Revenue'].sum()
rev_day = rev_day.reindex(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'])
print("\nRevenue by Day of Week:")
print(rev_day)

# Revenue by hour
rev_hour = df.groupby('order_hour')['Revenue'].sum().sort_index()
print("\nRevenue by Hour of Day:")
print(rev_hour)

# Weekend vs Weekday
rev_weekend = df.groupby('is_weekend')['Revenue'].sum()
rev_weekend.index = rev_weekend.index.map({0: 'Weekday', 1: 'Weekend'})
print("\nRevenue: Weekend vs Weekday:")
print(rev_weekend)

corr_rating_revenue = df['Rating'].corr(df['Revenue'])
corr_rating_profit = df['Rating'].corr(df['Profit'])

print("\nCorrelation between Rating and Revenue:", round(corr_rating_revenue, 3))
print("Correlation between Rating and Profit:", round(corr_rating_profit, 3))

